# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Definition of infra-related environment variables

variables:

  # DEV Environment
  ENVIRONMENT: mlw-dp100-labs
  RESOURCE_GROUP: rg-dp100-labs
  LOCATION: centralus
  NAMESPACE: mlopsdevtmpl
  SERVICECONNECTION_RG: mlops
  SERVICECONNECTION_WS: conn-mlops-aml-bsc-dev-tmpl
  AMLWORKSPACE: aml$(NAMESPACE)
  STORAGEACCOUNT: sa$(NAMESPACE)
  KEYVAULT: kv$(NAMESPACE)
  APPINSIGHTS: ai$(NAMESPACE)
  CONTAINERREGISTRY: cr$(NAMESPACE)
